.TH SREF 1 sref\-VERSION
.SH NAME
sref \- simple reference image board
.SH SYNOPSIS
.B sref
.RB [ \-hv ]
.RB [ \-\- ]
.RI [ files
.IR ... ]
.SH DESCRIPTION
.B sref
is a quick clone of pureref.
.B sref
is a tool to display a collection of images all in the same graphical window, allowing to pan around, move and scale images.
.SH OPTIONS
.TP
.B \-v
prints version information to stderr and exit.
.TP
.B \-h
prints a short usage help and exit.
.SH CUSTOMIZATION
sref is customized by creating a custom
.PA config.h
and (re)compiling the source code.
.SH AUTHORS
See the LICENSE file for authors.
.SH LICENSE
See the LICENSE file for copyright and license details.
